name: Issue Templates
description: Configuration for issue templates
body: Please use one of the templates below to create an issue
blank_issues_enabled: false
contact_links:
  - name: PyProcessor Documentation
    url: https://github.com/Lungren2/PyProcessor/tree/main/docs
    about: Check the documentation before opening an issue
  - name: GitHub Discussions
    url: https://github.com/Lungren2/PyProcessor/discussions
    about: Please ask and answer questions here
