name: Build & Release

on:
  push:
    branches: [main]
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python scripts/dev_tools.py deps --install --extras dev

      - name: Download FFmpeg
        run: |
          python scripts/build_tools.py ffmpeg

      - name: Build application
        run: |
          python scripts/build_tools.py build --skip-ffmpeg

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyprocessor-build
          path: dist/PyProcessor/

      - name: Create installer (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Install NSIS
          choco install nsis -y

          # Create installer
          python scripts/build_tools.py package --skip-build

      - name: Create Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            PyProcessorInstaller.exe
          draft: true
          prerelease: false
          generate_release_notes: true
