name: Code Quality

on:
  push:
    branches: [main, dev]
    paths:
      - "**.py"
  pull_request:
    branches: [main, dev]
    paths:
      - "**.py"

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy isort bandit

      - name: Check code formatting with black
        run: |
          black --check .

      - name: Check import sorting with isort
        run: |
          isort --check-only --profile black .

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check types with mypy
        run: |
          mypy --ignore-missing-imports pyprocessor

      - name: Check security issues with bandit
        run: |
          bandit -r pyprocessor -x tests
